taosdata/tsbs

pkg/targets/tdengine/creator.go, pkg/targets/tdengine/serializer.go, pkg/targets/tdenginesml/creator.go
=> Revert "enh: generate ns timestamp and create database with ns"

internal/inputs/generator_data.go, pkg/targets/constants/constants.go, pkg/targets/csv/implemented_target.go, pkg/targets/csv/serlizer.go, pkg/targets/initializers/target_initializers.go
=> feat: generate csv data

scripts/tsdbComp/common.sh, scripts/tsdbComp/installEnv.sh, scripts/tsdbComp/installTsbsCommand.sh, scripts/tsdbComp/loadAllcases.sh, scripts/tsdbComp/logger.sh, scripts/tsdbComp/queryAllcases.sh, scripts/tsdbComp/test.ini, scripts/tsdbComp/tsdbComparison.sh
1. correct variable names in load and query scripts and add logging functions
2. add  logger.sh to add logging 
3. add  common.sh  
4. capture the system information and machine specs during the test
5. verify if the minimum runtime configuration is met.
=> fix: correct variable names in load and query scripts and add logging functions

scripts/tsdbComp/installEnv.sh, scripts/tsdbComp/tsdbComparison.sh
fix some errors in commond
1.Update the installation script to unset the client IP when testing on a single machine 
2.fix some errors in commond
=> Fix: Update the installation script to unset the client IP when testing on a single machine 

scripts/tsdbComp/full_cycle_minitest_loading.sh, scripts/tsdbComp/full_cycle_minitest_query.sh, scripts/tsdbComp/full_cycle_minitest_query_loading.sh, scripts/tsdbComp/queryAllcases.sh, scripts/tsdbComp/querytest.sh
=> refactor: improve script structure and logging in query scripts

scripts/tsdbComp/full_cycle_minitest_query.sh
=> 修改TDengine查询时的命令行参数

scripts/tsdbComp/gen_report/load_report.py, scripts/tsdbComp/gen_report/query_report.py
=> fix: set matplotlib to use non-interactive backend for report generation

scripts/tsdbComp/load_report.py, scripts/tsdbComp/query_report.py
feat: add input file existence check and database type validation in report
=> feat: add input file existence check and database type validation in report 

scripts/tsdbComp/full_cycle_minitest_loading.sh, scripts/tsdbComp/full_cycle_minitest_query_loading.sh, scripts/tsdbComp/install_env.sh
=> 解决influxdb3启动失败

scripts/tsdbComp/full_cycle_minitest_query.sh, scripts/tsdbComp/query_test.sh
=> fix: simplify TDengine format handling in query scripts

scripts/tsdbComp/query_test.sh
=> fix: update format handling in query test scripts

scripts/tsdbComp/install_env.sh
=> test script：check glibc version

scripts/tsdbComp/common.sh, scripts/tsdbComp/full_cycle_minitest_loading.sh, scripts/tsdbComp/full_cycle_minitest_query_loading.sh, scripts/tsdbComp/install_env.sh
=> test scripts

scripts/tsdbComp/install_tsbs_cmd.sh, scripts/tsdbComp/tsbs_comparison.sh
fix: add return statement for Go installation check in TSBS script
=> fix: add return statement for Go installation check in TSBS script

scripts/tsdbComp/common.sh, scripts/tsdbComp/full_cycle_minitest_loading.sh, scripts/tsdbComp/full_cycle_minitest_query_loading.sh, scripts/tsdbComp/test.ini, scripts/tsdbComp/tsbs_test.sh
=> test influxdb3

.gitignore, scripts/tsdbComp/common.sh, scripts/tsdbComp/install_tsbs_cmd.sh, scripts/tsdbComp/tsbs_comparison.sh
fix: improve environment setup scripts for Go and TSBS installation
fix: add log directory to .gitignore for cleaner repository 
=> fix: improve environment setup scripts for Go and TSBS installation

scripts/tsdbComp/full_cycle_minitest_loading.sh, scripts/tsdbComp/full_cycle_minitest_query_loading.sh, scripts/tsdbComp/install_env.sh, scripts/tsdbComp/install_tsbs_cmd.sh, scripts/tsdbComp/test.ini, scripts/tsdbComp/tsbs_comparison.sh
=> test script

scripts/tsdbComp/tsbs_test.sh
=> Add scenario4 to tsbs_test.sh and update help message

scripts/tsdbComp/common.sh, scripts/tsdbComp/full_cycle_minitest_loading.sh, scripts/tsdbComp/full_cycle_minitest_query.sh, scripts/tsdbComp/full_cycle_minitest_query_loading.sh
=> test timescaledb

scripts/tsdbComp/common.sh, scripts/tsdbComp/tsbs_test.sh
=> Modify the default scene

scripts/tsdbComp/full_cycle_minitest_loading.sh
=> adjust disk_usage_nowal position in load_input.csv

scripts/tsdbComp/load_report.py, scripts/tsdbComp/query_report.py
=> update display name in chart
